### ISSUE TITLE
Next Sydney NodeSchool date / location / details discussion

### ISSUE THREAD

**Issue by rvagg** [nodeschool/sydney#1]
Open discussion on date, location and format, feel free to pitch an idea here so we can try and get another NodeSchool up before the end of 2014.

**Comment by DamonOehlman** [comment]
I think that's a great idea.  I've been talking with work about flying @maxogden out for some DAT related stuff (hangout in Sydney and do what he normally does) and we've all agreed in genera principal.  Just need to work out the dates, but it's likely that we could coordinate the next nodeschool with Max being in town...  also, I'm sure NICTA would be happy to host again if that was desired.

**Comment by rvagg** [comment]
@rprieto @DamonOehlman are we going to try and pull off an event on the international day? May 23rd?

**Comment by rprieto** [comment]
I'm pretty keen to help organise something. I've talked to a few people who would be interested in mentoring. Is this NodeSchool targeted to a more advanced level, or do you think same as last time?

**Comment by DamonOehlman** [comment]
That's right in the middle of the next CampJS right?  That being the case, I reckon I'm probably out...

**Comment by rvagg** [comment]
doh! it is too ... that counts me out too

**Comment by rprieto** [comment]
Ouch, didn't realise that... We could do it on another date?

**Comment by JedWatson** [comment]
I'm in to help with whatever, whenever. Will also be at CampJS.

**Comment by gingermusketeer** [comment]
Hi all,

I have been keen to help organise an event here before i leave Sydney (17th of April). Since arriving a few months ago i have been trying to find somewhere to host the event.

Let me introduce @iloire. He works for Atlassian. We had a chat today about running an event. He is going to help organise some space at Atlassian.

We are thinking of having it during the week after work for a couple of hours. Perhaps a Wednesday or Thursday.

Let me know what you think

**Comment by rvagg** [comment]
Great stuff @gingermusketeer, don't wait for us to give you a greenlight or anything, those who **do** get to make the decisions! Given my distance from Sydney I probably won't be able to make it but I'll keep an eye out for the date and perhaps it'll line up with something.

**Comment by rvagg** [comment]
Also relevant http://www.meetup.com/sydney-node-ninjas/messages/boards/thread/48801408

**Comment by gingermusketeer** [comment]
Thanks @rvagg. I will keep this thread updated

**Comment by iloire** [comment]
Hi all/@gingermusketeer !

I am seeing how we can organise the event in Atlassian's facilities next month so we can set the date.

**Comment by gingermusketeer** [comment]
@iloire Awesome. Let me know how you get on. April 8th/9th or 15th/16th works best for me.

**Comment by iloire** [comment]
So I booked two rooms for the 16th April at our offices (341 George St 2000). We will have good tables and chairs, power sockets, HD projectors and Wi-Fi (and pizza :)). Max amount of people: 30.

**Comment by supernoveau** [comment]
Awesome @iloire. Is registration via the Meetup group?

**Comment by gingermusketeer** [comment]
@almccann that is the plan. I need to organize it this week

**Comment by gingermusketeer** [comment]
Have not heard back from the meetup organisers. I have tried an alternative method of contact today.

If i hear nothing back tomorrow i will go to plan B which at the moment is a google form :(

**Comment by gingermusketeer** [comment]
Can someone have a look at https://github.com/nodeschool/sydney/pull/3

**Comment by JedWatson** [comment]
@gingermusketeer that site looks great!

I'm happy to help out & mentor. Also have two people who'd like to attend when we get registrations up.

The 16th is the evening after this month's SydJS (also at Atlasssian) so if we're lacking either mentors or attendees we should be easily able to fill some last minute spots then :)

**Comment by gingermusketeer** [comment]
@JedWatson Thanks for the feedback

We would love to have you help out

**Comment by gingermusketeer** [comment]
Here is what is left
- [x] Merge website PR
- [x] Announce via ti.to or meetup.com
- [x] Send out the details to
  - [x] Node ninjas group http://www.meetup.com/sydney-node-ninjas/messages/boards/
  - [x] GA students
  - [x] Sydjs mailing list sydjs@librelist.com
- [x] Find a few more mentors

**Comment by indieisaconcept** [comment]
@gingermusketeer I'm happy to mentor.

**Comment by JedWatson** [comment]
Going to tag a few potential mentors here... no obligation implied! :smile: 

@DamonOehlman @rprieto @aaronpowell @davidbanham @nkbt @cgiffard @amay0048 @bladey

... and if he's going to be in Sydney, @dcousens

How many mentors should we aim for?

**Comment by nkbt** [comment]
@JedWatson count on me.

**Comment by cgiffard** [comment]
@JedWatson I'll be there with @indieisaconcept.

**Comment by gingermusketeer** [comment]
Thanks everyone. I have heard back from an organiser of the node ninjas group. Waiting from the event to be announced....

**Comment by rprieto** [comment]
Hey @gingermusketeer, sorry for the delay, I'm about the send the Meetup invite. The [website](http://gingermusketeer.github.io/sydney/) seems down though, do you mind having a look? Can you also confirm what time the event starts/ends?

**Comment by gingermusketeer** [comment]
@rprieto I merged and deleted my branch this is where the website can be found now http://nodeschool.io/sydney/

**Comment by gingermusketeer** [comment]
@rprieto It is on the 16th of April from 18:00 till 21:00 :)

**Comment by gingermusketeer** [comment]
wow 3 spots left http://www.meetup.com/sydney-node-ninjas/

**Comment by gingermusketeer** [comment]
Did anyone who wanted to mentor miss out on getting a spot?

**Comment by dcousens** [comment]
Unfortunately I wont be in Sydney at the time.

Sorry guys,  would have otherwise.

**Comment by davidbanham** [comment]
Does that mean there are plenty of mentors now?

**Comment by indieisaconcept** [comment]
@gingermusketeer I didn't bother rsvp'ing since I was going to mentor and to leave spots for those that wanted to nodeschool.

**Comment by nkbt** [comment]
Hm, should I remove my RSVP then?

## 

Sincerely yours, Nikita Butenko
Google Talk: nik@butenko.me
Skype: nikita.butenko
Mobile: +61 450 264 801

**Comment by iloire** [comment]
What a success!
There are space for about 30-35 people sitting. Counting out mentors from the 30 spots should be fine if you don't mind standing up a bit or squeezing around attendants.

**Comment by JedWatson** [comment]
@iloire great.

Maybe we raise the attendee cap so mentors can all rsvp as well then? it's useful to be "attending" because then you're included in notifications and comments etc. on meetup.com

I'd suggest 35-40, to allow for ~5 mentors and there are always a couple of no-shows...

**Comment by iloire** [comment]
@JedWatson Good idea. That would simplify the pizza order as well :)

**Comment by gingermusketeer** [comment]
Can everyone add themselves to the waitlist and then let me know how i can find them? 

I will add a few mentors before opening up the rsvp to 40

**Comment by JedWatson** [comment]
ping @twalve

**Comment by amay0048** [comment]
This sounds cool, but I can't make it that night. Count me in for the next one tho :-)

**Comment by spicecoder** [comment]
Just found the discussion. I am offering to mentor . 
Cheers 
Pronab

**Comment by gingermusketeer** [comment]
Thanks everyone for helping out/coming along. It was a great night

**Comment by JedWatson** [comment]
Thanks @gingermusketeer and @iloire for organising it, and Atlasssian for hosting / food / drinks!
