### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by yoshuawuyts** [nodeschool/sydney#10]
In lieu of #8 we should adopt a CoC. Does anyone have a strong opinion on which one to use? I'm currently leaning towards either taking the Node Melbourne one or the Node.js one because I trust the people that made them, though admittedly I wouldn't know the difference between the two.

Keen to hearing more thoughts on this! (':

**Comment by nkbt** [comment]
SydJS is pretty good too: http://www.sydjs.com/about

**Comment by vitalbone** [comment]
Hi, just submitted a PR to get the ball rolling with this issue. Look forward to any feedback https://github.com/nodeschool/sydney/pull/14

**Comment by vitalbone** [comment]
Going to close this since we've settled on something for the time being. As always, please feel free to pick this back up if you'd like to discuss this further.
