### ISSUE TITLE
[19 Dec 2015] Sydney NodeSchool hosted at GeneralAssembly

### ISSUE THREAD

**Issue by nkbt** [nodeschool/sydney#11]
# RSVP

https://generalassemb.ly/education/node-school-hosted-at-ga/sydney/18837
## Call for mentors!

Please write an email to nik@butenko.me (or just leave a comment here) if you are keen to be a mentor with your Name, Pic and couple of words about yourself. So we can add you to the event page.

More details to come!

**Comment by indieisaconcept** [comment]
Myself & @cgiffard are happy to mentor. Will provide more detail later.

**Comment by JedWatson** [comment]
I'm in to mentor!

**Comment by DamonOehlman** [comment]
I think I should be ok to mentor too :)

**Comment by nkbt** [comment]
@indieisaconcept @JedWatson @DamonOehlman and everyone else, see you tomorrow at NodeSchool :fire:

**Comment by JedWatson** [comment]
See you there :)

I'm recording a new React Podcast episode in the morning so may be slightly late, have to line up with our guest in the US who doesn't have a lot of availability. Hopefully will be done before 10!

**Comment by nkbt** [comment]
Awesome :+1:

**Comment by indieisaconcept** [comment]
@nkbt apologies but unfortunately it looks like I now wont be able to make it due to a last minute family commitment. 

Hope it goes well.

**Comment by JedWatson** [comment]
@nkbt On my way now, see you soon!

**Comment by nkbt** [comment]
Thanks everyone that was great!

**Comment by DamonOehlman** [comment]
@nkbt really sorry I couldn't make it mate.  Everything has been a bit crazy and it completely snuck up on me and didn't even see the github notification until this morning.  Looks like it went really well so congrats!

**Comment by nkbt** [comment]
@DamonOehlman no worries! Thank you!
