### ISSUE TITLE
[9th of July 2016] NodeSchool with WomenWho Code event

### ISSUE THREAD

**Issue by ButenkoT** [nodeschool/sydney#12]
Call for mentors!

Please write an email to tanya@butenko.me (or just leave a comment here) if you are keen to be a mentor with your Name, Pic and couple of words about yourself. So we can add you to the event page. 

This event will be experimental, with support of Women Who Code, to encourage women join the community. 

Event will be hold on 9th of July 2016 at CoderFactory.

**Comment by nkbt** [comment]
I'm in

**Comment by JedWatson** [comment]
I'm in too, pending family commitments

**Comment by cgiffard** [comment]
Depending on the date, I'm interested!

**Comment by lyntco** [comment]
I'd love to join 😄

**Comment by rvagg** [comment]
I'm just seeing this now, sorry for being slow. I'm guessing this is the event that @rprieto wanted the NodeSchool stickers for. I handed ~100 to @indieisaconcept that I had left so he could pass them on to Romain but I've just discovered that I have another ~150 of them! What's the max head-count for this event? Do you think you'll need more than 100 of them and should I arrange to get the extras to someone for this.

Also, see https://github.com/nodeschool/sydney/issues/13 regarding the need for a new sticker design, we're still using the original design and other active chapters have been using their custom designs for a while now.

**Comment by ButenkoT** [comment]
@rvagg Well, I think max head-count will be 100 people, so I guess it will be enough of them for this event. Thanks!

And I completely support the idea about own Sydney design for NodeSchool!
