### ISSUE TITLE
Sydney NodeSchool design competition

### ISSUE THREAD

**Issue by rvagg** [nodeschool/sydney#13]
We're using up the last of the original NodeSchool stickers that I had done in bulk before the first event we ran, but that design has been out of date for a while now and we need to come up with a special Sydney version.

The way this works is that you take the basic guide template @ https://github.com/nodeschool/nodeschool.github.io/tree/master/images/make-a-sticker put the letters S Y D at the bottom and come up with a design for the rest of it that is both Sydneyish and NodeSchoolish. Examples from chapters around the world are shown at: http://nodeschool.io/hexdex.html

We know we have some great designers in Sydney so we should tap in to that resource and organise a competition of some style to come up with a design.

What we need is:
- A plan: timeline, how & where we manage it and how the final design is chosen from the candidates
- Someone to volunteer to facilitate and manage the process

/cc @rprieto

**Comment by vitalbone** [comment]
Hi! Not sure if this is still a thing but I couldn’t see a Sydney logo on the [hexdex](http://nodeschool.io/hexdex.html) so I’ve designed a nodeschool Sydney logo and was hoping to enter it. Please let me know if you’re happy for a late submission, and if uploading an SVG to this issue is the best place to put it 🎨  Thanks!

**Comment by vitalbone** [comment]
Thought I'd give this a nudge to see if anyone is interested in providing any thumbs up/down to the proposed design @rvagg @rpietro @nkbt @yoshuawuyts

**Comment by nkbt** [comment]
Looks awesome

**Comment by rprieto** [comment]
Agreed, very cool work @vitalbone!

**Comment by vitalbone** [comment]
Quite a few people seemed to get behind this proposal (full disclaimer - I helped design it 😅 ) -> https://github.com/nodeschool/sydney/pull/15

If it's not too much of a stretch, let's lock that one in for now so we can progress with other aspects of the organisation. We can always start this discussion up again, or even hold another design competition in the near future.

Please feel free to correct me if I've got this completely wrong. Just want to help push things along to get stuff ready for the next event 🌈

**Comment by vitalbone** [comment]
BTW new hexdex merged into nodeschool.io repo and viewable here -> https://nodeschool.io/hexdex
