### ISSUE TITLE
Stop. Collaborate & Listen.

### ISSUE THREAD

**Issue by vitalbone** [nodeschool/sydney#16]
Hi,

I'd like to become a collaborator/member of this repo please! Would love to contribute and help organise a nodeschool event sometime soon-ish, as well as breath some life back into the repo and website.

Thanks!

**Comment by vitalbone** [comment]
ping @rprieto @nkbt @yoshuawuyts. (Just looking for write access) 😃

**Comment by rprieto** [comment]
Hi @vitalbone, that sounds great! Looking forward to the next Node School 🏫  I'm not an admin on the repo but maybe @rvagg can help?

**Comment by vitalbone** [comment]
Thanks @rprieto. I already asked @rvagg on Twitter and he said that he doesn't have access to this repo either 😞  Is there anyone else that may be able to help?

**Comment by yoshuawuyts** [comment]
@vitalbone added to the repo - unfortunately I can't make you an Admin, but this should at least help you get going (: Cheers!

**Comment by vitalbone** [comment]
Thanks heaps @yoshuawuyts !!

**Comment by vitalbone** [comment]
Hey @yoshuawuyts would we be able to get @twalve (Syd.js Sharkie) as a collaborator on this repo as well, please? We've got another NodeSchool event coming up this week and he's helping coordinate a bunch of stuff. Thanks!

**Comment by yoshuawuyts** [comment]
@vitalbone done! - you're both admins now too :sparkles:

**Comment by vitalbone** [comment]
Oh wow! Once again, thank you very much 💖
