### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by vitalbone** [nodeschool/sydney#20]
Hi @rvagg, it's looking more and more likely that the next NodeSchool Sydney event will be happening sometime in October - details to come soon!

I was hoping you'd still be up for asking NodeSource if they'd be interested in helping out with getting the stickers printed, as you mentioned a while back - https://github.com/nodeschool/sydney/pull/15#issuecomment-251575359.

Lettuce know either way. Thanks!

**Comment by rvagg** [comment]
I can probably take care of that. Who is running the next nodeschool & where?

**Comment by vitalbone** [comment]
Awesome! Thanks! Let me know if you need help with anything design / sticker related.

Re: next event - We're aiming for sometime in mid October. I'm in the process of finalising the venue at the moment. I've put my hand up to run it and am more than happy to have others help out with organising. Mentor registration can be found here - https://goo.gl/JaonJT

**Comment by vitalbone** [comment]
@rvagg Hey Rod, just a ping to see if this issue has had a chance to progress at all. Would it be helpful if I went about organising the printing of the stickers and just sent you the details (cost) after we've received them back from the printers?

**Comment by vitalbone** [comment]
Progress update: I've ordered some stickers from StickerMule. It's happening 🙀

**Comment by vitalbone** [comment]
Stickers arrived this morning! Grab yours at the next event.

![stickers-v1](https://user-images.githubusercontent.com/5966259/30680450-0c2b012a-9ee3-11e7-8d2d-6307bf4880ec.jpg)

**Comment by rvagg** [comment]
really sorry I dropped the ball on this @vitalbone, they look great though! can't wait to get my hands on one for my laptop!

**Comment by vitalbone** [comment]
No worries @rvagg, all good 🙂  There are still a few left so I'll make sure to save one for you. FYI @DamonOehlman pointed out they're about double the size that they're meant to be so we'll call these the limited-edition first run 🤦‍♂️  Will get the size right on the next run.
