### ISSUE TITLE
Mentor Registration: NodeSchool Sydney October 2017

### ISSUE THREAD

**Issue by vitalbone** [nodeschool/sydney#21]
Hiya! 👋🏾

Our next event will be happening on **14th October**, from 1-5pm @ [Domain HQ in Pyrmont](https://goo.gl/maps/Zrh8bvSqXbC2)!

Sound off in this issue to join us as a mentor for this upcoming event.

---

Mentors should be familiar with the [core NodeSchool workshoppers](https://nodeschool.io/#workshopper-list) before the event.  

We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

**Comment by fwouts** [comment]
Happy to help as a mentor. I mostly have experience writing frontend, command-line and Electron code and not server code, but looking at the workshoppers it doesn't look like it would be an issue.

**Comment by DamonOehlman** [comment]
@vitalbone should be available to help.  As a heads up I think we'll be doing a NodeBots days on the 28 October so it might be preferable to target early October if possible.  If not, no worries :)

**Comment by vitalbone** [comment]
Awesome @DamonOehlman ! Thanks for the heads up on NodeBots, will see what we can manage date-wise but it might depend on what the venue can do. 🤖

**Comment by vitalbone** [comment]
Woot! Domain have give us the green light for our venue. I've updated the initial post with the event details.

**Comment by atatwalker** [comment]
Happy to help, I used to teach pure JS in high schools

**Comment by gwyneplaine** [comment]
I am available to help @vitalbone

**Comment by bguiz** [comment]
Available to mentor

**Comment by ButenkoT** [comment]
Can come and help up :)

**Comment by pickworth** [comment]
I can be a mentor 👍

**Comment by vitalbone** [comment]
Not too long to go now. Thanks heaps to everyone who has put their hand up to help mentor next week! 💚💛  There's been quite a bit of interest (80 signups so far) so we'll need as many hands on deck as we can get.

Just a heads up: The event starts at 1pm so it'd be great if mentors can get there 15 minutes beforehand to help welcome the attendees.

BTW For those that might have missed it, we've started a NodeSchool Sydney newsletter. You can see the first issue and subscribe [here](http://mailchi.mp/714d54509182/nodeschool-14th-october-domain-hq).

**Comment by LennyBoyatzis** [comment]
@vitalbone looking forward to it :+1:

**Comment by joshhendo** [comment]
I can come help be a mentor

**Comment by vitalbone** [comment]
Hey hey! I was thinking that to help welcome the attendees (we're up to 106 sign ups!) it would be great if the mentors could give a quick intro about themselves at the start of the event. Shouldn't take more than 30 seconds each, just a quick:

1. Your name
2. What you do
3. An interest outside of programming
4. Why you're here today

eg: Hi, my name's Vito. I work as a software developer at Thinkmill, writing a lot of JavaScript. When I'm not programming I'm renovating my house. I'm here today because I love helping people find that 'a-ha' moment when they're learning JavaScript.

No need to add yours to this thread, just something to have in the top pocket for tomorrow. Ok, see you all tomorrow!

@fwouts @nmors @joshhendo @LennyBoyatzis @ButenkoT @bguiz @DamonOehlman @gwyneplaine @atatwalker @cameronbourke

**Comment by DamonOehlman** [comment]
@vitalbone Hey mate - unfortunately I'm out for the weekend.  I had completely forgotten that I've got to ferry my kids around to a few things, so really can't make it... so sorry.

**Comment by vitalbone** [comment]
@DamonOehlman No probs pal. Good luck with ⛴ 'ing the kids.

**Comment by vitalbone** [comment]
Looping in @noviny

**Comment by vitalbone** [comment]
Thanks to everyone who was able to make it today. It turned out to be a really fun day of coding and learning. For those that were unable to make it, no probs at all, hopefully we'll see you at another event soon ❤️ 

Also, @fwouts, @noviny and @LennyBoyatzis had the great idea of starting up a Meetup page so it'd be easier for the attendees to stay in touch between events. Feel free to join up here -> [https://www.meetup.com/NodeSchool-Sydney](https://www.meetup.com/NodeSchool-Sydney)
