### ISSUE TITLE
Mentor Registration: NodeSchool Sydney March 24th, 2018 @ Domain

### ISSUE THREAD

**Issue by vitalbone** [nodeschool/sydney#23]
Hey hey mentors!

Our first NodeSchool for 2018 is happening on **March 24th** at **Domain HQ** in Pyrmont.

Chime in on this issue to join us as a mentor for this event.

---
Mentors should be familiar with the [Core NodeSchool workshoppers](https://nodeschool.io/#workshopper-list) before the event.

We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

---
**Mentors**
- [x] @bladey
- [x] @vitalbone
- [x] @LennyBoyatzis
- [x] @fwouts 
- [x] @ButenkoT
- [x] @joshhendo
- [ ] @nmors
- [ ] @bguiz
- [ ] @gwyneplaine
- [ ] @atatwalker
- [ ] @DamonOehlman
- [ ] @jesstelford 
- [ ] @JedWatson
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [ ] *you?*
- [x] @Noviny

**Comment by atatwalker** [comment]
Sorry, I'm no longer in Sydney

**Comment by vitalbone** [comment]
@atatwalker no probs, thanks for letting us know 🙂

**Comment by fwouts** [comment]
I'm in.

**Comment by ButenkoT** [comment]
Looks like 24th of March is free. I'm in

**Comment by ButenkoT** [comment]
@nkbt

**Comment by Noviny** [comment]
I am there.

**Comment by bladey** [comment]
@vitalbone I'll be there!

**Comment by joshhendo** [comment]
I'll be able to come :)

**Comment by joshhendo** [comment]
@vitalbone what time do you want mentors to arrive?

**Comment by vitalbone** [comment]
@joshhendo Good question. Would be great to have mentors arrive at 12.45pm. We can go through how the day will play out and answer any questions. Everyone else should be arriving from 1pm.

**Comment by pickworth** [comment]
Sorry @vitalbone won't be able to make it this time. Put me down for the next one please!

**Comment by vitalbone** [comment]
Massive thanks to everyone who was able to make it on Saturday! 💚💛 It was a great day, made even better thanks to our fantastic mentors helping everyone learn express and fixing all the bugs in the workshop :P

No probs if you weren't able to make it in the end. Hopefully we'll see you at another event later this year.

Can't wait for the next one 🎷
