### ISSUE TITLE
Mentor Registration: NodeSchool Sydney June 2nd, 2018 @ Domain

### ISSUE THREAD

**Issue by vitalbone** [nodeschool/sydney#24]
Here we go again!

The next NodeSchool event is happening on **June 2nd** at **Domain HQ** in Pyrmont.

Chime in on this issue to join us as a mentor for this event.

---

Mentors should be familiar with the [Core NodeSchool workshoppers](https://nodeschool.io/#workshopper-list) before the event.

We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.

---

**Mentors**
- [x] @nmors
- [x] @fwouts
- [x] @bladey
- [x] @vitalbone
- [x] @LennyBoyatzis
- [ ] @cameronbourke
- [ ] @ButenkoT
- [x] @Noviny
- [ ] @joshhendo
- [ ] @bguiz
- [ ] @gwyneplaine
- [ ] @DamonOehlman
- [ ] @jesstelford
- [ ] @JedWatson
- [ ] you?
- [ ] you?
- [ ] you?
- [ ] you?
- [ ] you?
- [ ] you?

**Comment by pickworth** [comment]
Count me in!

**Comment by fwouts** [comment]
✓

**Comment by vitalbone** [comment]
Ping @ButenkoT @Noviny @joshhendo @bguiz @gwyneplaine @DamonOehlman 🙂

**Comment by incessantmeraki** [comment]
Count me in as well :D

**Comment by Noviny** [comment]
I em in

**Comment by pickworth** [comment]
@daryl-d

**Comment by bladey** [comment]
I'll be there @vitalbone

**Comment by Nicosoft** [comment]
Hi there,
I'd like to help you guys!
I have experience with Node (api/lambda functions) and more recently writing lambda functions for Alexa.

**Comment by pickworth** [comment]
Running 15-20 minutes late as there is a crash on the M2. Sorry

**Comment by vitalbone** [comment]
Great turn out. Thanks to everyone who came along and helped out. Extra big thanks to @bladey for the delicious gelato 🍦❣️
