### ISSUE TITLE
Mentor Registration: NodeSchool Sydney October 27th, 2018 @ Domain

### ISSUE THREAD

**Issue by vitalbone** [nodeschool/sydney#27]
We're back!

The next NodeSchool event is happening on Saturday, October 27th at Domain HQ in Pyrmont.

Chime in on this issue to join us as a mentor for this event.

---
Mentors should be familiar with the [Core NodeSchool workshoppers](https://nodeschool.io/#workshopper-list) before the event.

We also encourage mentors to review the [NodeSchool Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).

---

**Comment by vitalbone** [comment]
Who's keen?

- [x] @incessantmeraki
- [x] @nmors
- [x] @shannondussoye
- [x] @saussayjesica
- [x] @joshhendo
- [x] @LennyBoyatzis
- [ ] @albertstill
- [ ] @bladey
- [ ] @ButenkoT
- [ ] @fwouts
- [ ] @nkbt
- [ ] @Noviny

**Comment by fwouts** [comment]
@vitalbone will this be a self-guided session or will you be going through a specific workshop?

**Comment by vitalbone** [comment]
@fwouts I was hoping someone would be interested in walking through how to build a super simple node+react app. Could that someone be you???!!!

If there are no takers then I can always do it.

**Comment by ButenkoT** [comment]
I'm keen to help on the day but don't want to sign in and no show again. So I just put it to my calendar and will confirm closer to the day.

About node+react workshop we are doing one on 10th of November. Maybe @saussayjesica is interested?

**Comment by incessantmeraki** [comment]
Count me in

**Comment by fwouts** [comment]
@vitalbone  subject sounds interesting. Would you use `create-react-app` + a simple `express` server, or some kind of all-in-one framework? I'm not sure what's best these days :)

**Comment by shannondussoye** [comment]
Count me in

**Comment by vitalbone** [comment]
@fwouts yeah probs just `CRA` and `express`, just enough for someone to understand how they work together and hopefully give them a base they can build on their own. Are you coming along?!

@ButenkoT All good - it'd be great to see you but I know how busy you are!

@saussayjesica We'd love for you to run the workshop, but only if you're keen - no pressure!

**Comment by saussayjesica** [comment]
hey @vitalbone 👋 the workshop i'm running for node girls is a create react app. i'd be happy to run the workshop for node school. does it need to include an express server?

**Comment by vitalbone** [comment]
Hi @saussayjesica thanks for putting your hand up! Sounds like there's a bit of cross over with the workshop you're running at Node Girls, which is great.

I thought the attendees might be keen to build a client + server app so they can call themselves "FULL STACK" 😜

If you feel like React + Node by yourself is too much then we could split it?! You could start with 1 hr of React and then I can connect it to a Node app! That'd be fun right?

What kind of site do you build in your create app workshop? Is there a repo I could look at?

**Comment by pickworth** [comment]
Count me in!

**Comment by vitalbone** [comment]
Hey @shannondussoye 👋 I received an email notification saying you're in but it doesn't seem to appear on this thread so I've added you to the list of mentors.

**Comment by saussayjesica** [comment]
> Hi @saussayjesica thanks for putting your hand up! Sounds like there's a bit of cross over with the workshop you're running at Node Girls, which is great.
> 
> I thought the attendees might be keen to build a client + server app so they can call themselves "FULL STACK" 😜
> 
> If you feel like React + Node by yourself is too much then we could split it?! You could start with 1 hr of React and then I can connect it to a Node app! That'd be fun right?
> 
> What kind of site do you build in your create app workshop? Is there a repo I could look at?

@vitalbone here's the link to the repo if you want to check it out https://github.com/saussayjesica/emoji-eats
I still need to write up instructions

**Comment by vitalbone** [comment]
@saussayjesica That looks amazing! A great example app for learning React. 

We'd love for you to present it on Saturday. I think the easiest way to do the workshop would be if you present the React app and then I can swap out the dummy data for data being served by a Node app. How does that sound?

**Comment by saussayjesica** [comment]
@vitalbone sure that sounds great. will you be sending out an email before sat? would be great if they could have the following installed before the workshop 

- Chrome: https://www.google.com/chrome
- VS Code: https://code.visualstudio.com/ (or other text editor)
- Node/npm: https://nodejs.org/en/ (install ‘recommended for most users’ version)

Prerequisites
- Some HTML and CSS knowledge
- Some experience with the command line

**Comment by vitalbone** [comment]
Great. Yup, I'll send an email out and give everyone the heads up! See you Saturday 🌈

**Comment by joshhendo** [comment]
I'll be able to come :)

**Comment by saussayjesica** [comment]
> Great. Yup, I'll send an email out and give everyone the heads up! See you Saturday 🌈

would you mind also adding the following if you haven't already sent the email :)
- React Dev Tools: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en

**Comment by vitalbone** [comment]
@saussayjesica I sent it out on Tuesday! No probs, we can get them to install it before or during the demo.
