### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by pickworth** [nodeschool/sydney#28]
Just wondering if we Have a Slack channel setup for nodeschool Sydney.

If not let's create one?

If so, this would be a good place for people to find it.

Cheers
Nathan

**Comment by vitalbone** [comment]
Great idea Nathan!
I'd been holding off on this till the community got a little larger but we're nearly at 600 members on the Meetup group so now seems like as good a time as any to get something going.

I'll create something this week and let y'all know when it's up and running.

**Comment by vitalbone** [comment]
The Official NodeSchool Sydney Slack Workspace™ has been created 🌈

This **join** link will be available for ~30 days so we'll need to get something more permanent up eventually but it'll do for now > https://bit.ly/2RXCsfz

Sign in/up and let's continue to build our tiny little digital community!
