### ISSUE TITLE
Mentor Registration: NodeSchool Sydney September 14th 2019 @ Microsoft Reactor

### ISSUE THREAD

**Issue by vitalbone** [nodeschool/sydney#29]
2019 - Better late than never!

The next NodeSchool event is happening on Saturday, September 14th at Microsoft's new event space - [Reactor](https://developer.microsoft.com/en-us/reactor/Location/Sydney), located in the CBD.

🛎 Chime in on this issue to join us as a mentor for this event.

---
Mentors should be familiar with the [Core NodeSchool workshoppers](https://nodeschool.io/#workshopper-list) before the event.

We also encourage mentors to review the [NodeSchool Mentor Best Practices wiki page](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).

---

**Comment by joshhendo** [comment]
I've put it in my calendar, most likely be able to make it but I'll confirm closer to the event

**Comment by vitalbone** [comment]
Nice one @joshhendo ! Look forward to (hopefully) seeing you on the day.

**Comment by vitalbone** [comment]
🗣 Roll call:

- [x] @joshhendo
- [x] @freemany
- [x] @nmors
- [x] @jvieirar
- [x] @limenutt
- [x] @freemany
- [x] @earthtone
- [ ] @ticidesign
- [ ] @incessantmeraki
- [ ] @shannondussoye
- [ ] @saussayjesica
- [ ] @LennyBoyatzis
- [ ] @albertstill
- [ ] @bladey
- [ ] @ButenkoT
- [ ] @fwouts
- [ ] @nkbt
- [ ] @Noviny

**Comment by vitalbone** [comment]
Oh probs should've also mentioned - let me know if you're interested in doing a presentation. Show off something cool you've been working on or a do a tutorial on how to build something with JS 🙌

**Comment by incessantmeraki** [comment]
i can't make it this time unfortunately. here in Auckland for few months.

**Comment by ticidesign** [comment]
@vitalbone you can put me down as a mentor.

**Comment by vitalbone** [comment]
> i can't make it this time unfortunately. here in Auckland for few months.

Thanks for letting us know @incessantmeraki. You'll be missed!

**Comment by vitalbone** [comment]
> @vitalbone you can put me down as a mentor.

Woot Woot!!

**Comment by trust2065** [comment]
I can't go on this quarter, but I'm willing to be a mentor in the next and future events.
I am a frontend developer and also a primary school teacher. 😀

**Comment by vitalbone** [comment]
Thanks @trust2065. Will ping you when we announce the next event.

**Comment by earthtone** [comment]
@vitalbone I would love to help out as a mentor at next quarter's event if you still need people.

**Comment by vitalbone** [comment]
Thanks @earthtone, will add you to the list of potential mentors.

**Comment by freemany** [comment]
Hi @vitalbone,
I would like to be a mentor. Thanks.

**Comment by vitalbone** [comment]
@freemany fantastic - welcome aboard!

**Comment by limenutt** [comment]
Hi @vitalbone,
I’d love to mentor someone there. I can also quickly talk about debugging as we find that it’s a skill many junior devs lack.

**Comment by jvieirar** [comment]
Hi @vitalbone,
Please let me join you as a mentor =D and send me all the info I may need to know before the meetup!
Thanks,
Juan.

**Comment by pickworth** [comment]
@vitalbone tick my box please! :tada:

**Comment by vitalbone** [comment]
@limenutt awesome! A talk on debugging would be great too.

**Comment by vitalbone** [comment]
@jvieirar brilliant! I'll add an invite link to our Slack channel for all further communications.

**Comment by vitalbone** [comment]
@nmors nice! ticked!

**Comment by vitalbone** [comment]
I recommend heading over to the Slack channel - https://join.slack.com/t/nodeschoolsydney/shared_invite/enQtNzM3ODg3MzEyMzM4LWViNDEwMzY5ODY0Y2VmZGIwZGQ0YWZiZDA0YzNmODIwMzEzNjJlMWVjMTQ4ZDVkNjQ3NmI1YzlmOWJhYjIyZTY

This link will expire in 30 days

**Comment by DeveloperAlan** [comment]
Happy to help out as well!

**Comment by vitalbone** [comment]
Thanks @DeveloperAlan ! I think we're good for this event but will make sure to let you know for the next one 🙂

**Comment by ticidesign** [comment]
@vitalbone sorry for the last minute notice but I won't be able to make this Saturday.

**Comment by vitalbone** [comment]
@ticidesign no probs. Thanks for letting us know! You'll be missed.

**Comment by vitalbone** [comment]
Looking forward to seeing everyone who can make it tomorrow! Feel free to come a little earlier to help setup and welcome attendees if you'd like. 

We're going back to the original NodeSchool style tomorrow. That means there won't be a workshop to follow along throughout the day. Instead it'll be focused on letting everyone learn at their own pace through the [workshoppers](https://nodeschool.io/#workshoppers).

![tomoz](https://user-images.githubusercontent.com/5966259/64837164-7323a180-d630-11e9-8704-17c9b7a9dae3.jpg)
_I love these [Glitch](https://glitch.com/) images_

**Comment by vitalbone** [comment]
Thanks to everyone who showed up on Saturday! See y'all at the next one. We're thinking end of November.
