### ISSUE TITLE
Request for invite and next NodeSchool in Sydney

### ISSUE THREAD

**Issue by sasikanth** [nodeschool/sydney#8]
Hi Guys, 

I would like to know the next NodeSchool in Sydney and get an invite to join. 

Thanks,
Sasi

**Comment by Skilly** [comment]
I too will be grateful to take part in the next event

**Comment by writemike** [comment]
Just missed the last one! Would love to join the next. Thanks!

**Comment by mendokusai** [comment]
At this stage, since gingermusketeer left the continent, NodeSchool Sydney needs someone to take the helm and organize the event.

**Comment by yoshuawuyts** [comment]
Hey, I'd be happy to help mentor in a future edition of Nodeschool Sydney. Not sure I'd be comfortable taking the helm but I've successfully helped organize a few events in Amsterdam, and would love to give a hand while I'm in town (until the start of September). Cheers! 🙌✨

**edit [08/15]**: I'll be around until halfway through October
**edit [10/15]**: I'll be around until the end of time :rocket:

**Comment by yoshuawuyts** [comment]
Hey, I talked to one of the guys from GA; he was on board to help sort out sponsorship / locations. I'll figure that stuff out on my end; what I'm looking for from you is to help out mentor! Just post in here if you're interested. I'll aim for a Nodeschool in December during a weekday, does that sound good? Cheers!

cc/ @hughsk @jesstelford 

**edit: tl;dr**
- meetup in December
- talking to General Assembly for sponsorship
- we need mentors

**Comment by hughsk** [comment]
I'm 90% sure Vibewire would love to host :)

Happy and available to mentor any weekday the first two weeks of December except for the 2nd! :cake:

**Comment by yoshuawuyts** [comment]
@hughsk that'd be rad! Could you reach out to Cass to see if it's possible, she's a bit slow to reply to my messages, hah (':

**Comment by hughsk** [comment]
Sure thing, done! Also @rvagg @damonoehlman are you free and/or interested in joining in at all? :)

**Comment by rvagg** [comment]
Interested, unsure if available. Node.js Interactive _may_ be a blocker, it's the 7th so if I end up going then I'd have to block out some days around that.

**Comment by nkbt** [comment]
@yoshuawuyts I was going to announce this on NodeJS meetup =)

It was actually me with @ButenkoT talking to GA about it

**Comment by yoshuawuyts** [comment]
@nkbt hah, must've had the same idea! Reached out to one of the other GA teachers at SydJS yesterday since he brought half of his students haha. But if you're already in touch, would you mind sharing some more details? Do you have a date? Location? Sponsorship? What can we do to help?

**Comment by nkbt** [comment]
@yoshuawuyts @ButenkoT works in GA at the moment =). We were discussing things with Gigi. Date is not defined yet, they have some legal questions to solve, but approximately it is going to be in Dec.

In terms of help - everything as usual: mentors and attendees! I am pretty sure the date will be concrete very soon.

I was talking to @rprieto about this on last node ninjas. We may need some more help, but can't talk about it yet.

**Comment by yoshuawuyts** [comment]
Cool, so location + date should be known soon. In case GA doesn't work out, I believe @hughsk has the green light to go ahead with Vibewire. 

@nkbt Will food + drinks be taken care of? Do we need sponsors for that?

Perhaps it'd also be rad to order some stickers for Nodeschool Sydney / stuff we're doing workshops about. Also: which workshops should we do? I was thinking something along the lines of JavaScripting / learnyounode as a baseline + some personal flavors. e.g. @hughsk has graphics stuff, @rvagg has built a few too, I could write one on Mercury / vdom, etc. (':

**Comment by geege-out** [comment]
@yoshuawuyts Hi, I've been talking with @nkbt about hosting Node school at GA. I have a date available and the space for you to use. but you'll need to organise your own mentors. 

Happy to discuss further.

**Comment by yoshuawuyts** [comment]
@geege-out your friendly colleague sent me your contact details, I've sent you an email with all the questions I had. Looking forward to your reply! :sparkles:

---

> 1. What is the date you had in mind? For us the first or second week of December would be ideal.
> 2. How many people can the space facilitate?
> 3. Do we need to provide any additional supplies (e.g. power adapters and the like)?
> 4. Will there be wifi? Though we usually instruct attendees to download node + workshops beforehand, there will always be those that don't have it installed.
> 5. Will GA sponsor food / drinks?
> 6. Is there a maximum time frame for the event? I think we're aiming for a 6pm - 10pm style event.

**Comment by nkbt** [comment]
https://github.com/nodeschool/sydney/issues/11

@yoshuawuyts let's talk today at NodeNinjas meetup (if you are here)

**Comment by yoshuawuyts** [comment]
@nkbt yeah, I think we should talk

**Comment by jesstelford** [comment]
Unfortunately I won't be available to mentor. Have fun - it'll be an awesome event :D

**Comment by ianhobbs** [comment]
hi i'd love to be in the next node school . Please add me as a member.

**Comment by vitalbone** [comment]
Hi all, closing this thread.

If anyone is keen on mentoring at a NodeSchool Sydney event, we'll be hosting the next one @ Domain on **Saturday, 14th October**. For more details, check out this issue - https://github.com/nodeschool/sydney/issues/21

Would love to see you there!
