### ISSUE TITLE
Hei hei a nodejs dudette for the sydney team

### ISSUE THREAD

**Issue by viqueen** [nodeschool/sydney#9]

**Comment by yoshuawuyts** [comment]
@viqueen hey! In case you're interested in helping out, we're putting some stuff together for the next Nodeschool in December on #8 (':

**Comment by vitalbone** [comment]
Hi @viqueen, going to close this issue but would love for you get involved in the next NodeSchool Sydney event, if you're still interested?!

Please check out this issue for more details - https://github.com/nodeschool/sydney/issues/21
